LangString addOrReinstall ${LANG_FINNISH} "Lisää tai asenna osat uudelleen"
LangString alreadyInstalled ${LANG_FINNISH} "Jo asennettu"
LangString alreadyInstalledLong ${LANG_FINNISH} "${PRODUCTNAME} ${VERSION} on jo asennettu. Valitse toimenpide ja jatka valitsemalla Seuraava."
LangString appRunning ${LANG_FINNISH} "{{product_name}} on käynnissä. Sulje se ensin ja yritä uudelleen."
LangString appRunningOkKill ${LANG_FINNISH} "{{product_name}} on käynnissä.$\nValitse OK, niin se suljetaan."
LangString chooseMaintenanceOption ${LANG_FINNISH} "Valitse ylläpitotoimenpide."
LangString choowHowToInstall ${LANG_FINNISH} "Valitse, miten ${PRODUCTNAME} asennetaan."
LangString createDesktop ${LANG_FINNISH} "Luo työpöytäkuvake"
LangString dontUninstall ${LANG_FINNISH} "Älä poista asennusta"
LangString dontUninstallDowngrade ${LANG_FINNISH} "Älä poista asennusta (vanhempaan versioon siirtyminen ilman poistoa on poissa käytöstä)"
LangString failedToKillApp ${LANG_FINNISH} "{{product_name}} ei sulkeutunut. Sulje se itse ja yritä uudelleen."
LangString installingWebview2 ${LANG_FINNISH} "Asennetaan WebView2..."
LangString newerVersionInstalled ${LANG_FINNISH} "Uudempi ${PRODUCTNAME}-versio on jo asennettu. Vanhempaa versiota ei kannata asentaa. Jos silti haluat, poista nykyinen versio ensin. Valitse toimenpide ja jatka valitsemalla Seuraava."
LangString older ${LANG_FINNISH} "vanhempi"
LangString olderOrUnknownVersionInstalled ${LANG_FINNISH} "Järjestelmässä on $R4 versio ohjelmasta ${PRODUCTNAME}. Nykyinen versio kannattaa poistaa ennen uutta asennusta. Valitse toimenpide ja jatka valitsemalla Seuraava."
LangString silentDowngrades ${LANG_FINNISH} "Vanhempaan versioon siirtyminen on poissa käytöstä tässä asentimessa. Käytä graafista asenninta.$\n"
LangString unableToUninstall ${LANG_FINNISH} "Asennusta ei voitu poistaa."
LangString uninstallApp ${LANG_FINNISH} "Poista ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_FINNISH} "Poista asennus ennen uutta asennusta"
LangString unknown ${LANG_FINNISH} "tuntematon"
LangString webview2AbortError ${LANG_FINNISH} "WebView2:n asennus epäonnistui. Sovellus ei toimi ilman sitä. Käynnistä asennin uudelleen."
LangString webview2DownloadError ${LANG_FINNISH} "Virhe: WebView2:n lataus epäonnistui - $0"
LangString webview2DownloadSuccess ${LANG_FINNISH} "WebView2-asennin ladattu"
LangString webview2Downloading ${LANG_FINNISH} "Ladataan WebView2-asenninta..."
LangString webview2InstallError ${LANG_FINNISH} "Virhe: WebView2:n asennus päättyi koodiin $1"
LangString webview2InstallSuccess ${LANG_FINNISH} "WebView2 asennettu"
LangString deleteAppData ${LANG_FINNISH} "Poista sovelluksen tiedot"
